name: actionlint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  actionlint:
    uses: thadiust/workflow-python/.github/workflows/reusable-actionlint.yml@c96f62483294eacee7ddafb639cd2185e91e6f0f # v1.0.8
    with:
      validate_root_action_yml: true
